logo:
  nav_mobile: images/logo-apollo-space-left.svg
  subbrand: images/logo-apollo-subbrands-developers-space.svg
  title: Apollo
  subtitle: Developers
  url: http://dev.apollodata.com/
favicon: images/favicon.png

nav_links:
  'React':
    url: http://dev.apollodata.com/react
  'Angular':
    url: http://dev.apollodata.com/angular2
  'iOS':
    url: http://dev.apollodata.com/ios
  'Android':
    url: http://dev.apollodata.com/android
  '原生 JS':
    url: http://dev.apollodata.com/core
  '服务端':
    url: http://dev.apollodata.com/tools
    separator: true
  '博客':
    url: https://medium.com/apollo-stack
    target: _new
  '社区':
    url: http://dev.apollodata.com/community
